language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - pypy

install:
  - pip install --use-mirrors -r test-requires.txt

script:
  - python test.py

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
